appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: UbwhbxeQMus8N1eWG5G/JsmXEcDHlBbPlwM3dh2BdtY3Zf+I9lp1QmT2xioWsoLsolLnJZU1gnv/YHWQenDK8tPCjfZB87tDkcTXQqELYO3a/CTEXszkW8nQkeWEFo4isve4IeTOrgOt7pNIPMO5IzBEXToblBydx9NcaazOn0g7VkjAd27oS3DJ7Xf/liEya+uwtChdAuUxUDvPiivnJXbYJNI8M/u7wEHzFplxB6z6awhLxi7CDLwMzPbhHZv2shO24OKRpf8Dk8SVNsll0z1DtDaram/uUCke0u6Q4ZymFwvsUr9bdO7oa6GetqDX4dKA0FI2sFoQryYHmC5wzyH/oT/ZrxLb9wO8DH2BsBAxNDg5Kbzpg2hsSzB02agsbcGViayCTgsgkXl6s49MXpba7esmnW2K7icnG143elXxmEWhaX5m72pQ3Gm0n8QxTs6wIFYYs4AZKQm6XFuSWcurIG8TajXnJ3IL+cvwlyB8isJv2Qcqa8Fa3ZA9jT0wecUzYMJqHr5LIjVHar+8uj6o47uRI/v0l7T63os5iKpfw9f5N+09FPOULnt1iTo0EF59OFndvaTyY40EVwhdEguzrv6MNiBXBbI3edUsXdOO6h1PCqZGSr1S8V8ymMMI53A5L7IbGPOzViicVemnIX07VNmiyaZAsru98zCjZlg=}
provider:
  win: azure
